### ISSUE TITLE
Publish command set?

### ISSUE THREAD

**Issue by xylo04** [n8jja/Pat-Vara#1]
Hi @n8jja, thanks for taking this up!

You said in the [Pat VARA issue](https://github.com/la5nta/pat/issues/228#issuecomment-877575144) that you have been in contact with VARA's author Jose Alberto Nieto Ros and that he gave you command set documentation. Is that something that you can share widely in this repo, or does Jose want to keep the command set documentation somewhat proprietary? Can you at least share it with me and other Pat developers, or do we need to get in contact with Jose individually?

Thanks for spurring this conversation!

P.S. I tried to get a hold of you by email at n8jja.com, but it couldn't be delivered; please double-check your DNS MX record.

**Comment by n8jja** [comment]
Hi!

Yes...the email issue has been fixed!  I have posted the command list to the repo as of today.  Please let me know if you have any other questions!

Jeremy
N8JJA
