### ISSUE TITLE
vARIM code might help?

### ISSUE THREAD

**Issue by WheezyE** [n8jja/Pat-Vara#2]
Hey, thank you for your work with VARA in Pat. There’s another program called vARIM that’s open source and communicates with VARA. I don’t know much about what’s required to understand VARA’s transport layer and whatnot, but thought maybe the vARIM code or dev might speed things up here too so you don’t have to reverse engineer as much

73
KI7POL

**Comment by n8jja** [comment]
Greetings!

I was unaware of that system.  I'll have a look and see what it contains.  Thanks very much for letting me know!

Jeremy
N8JJA

**Comment by xylo04** [comment]
If others also go looking for this, the home page is https://www.whitemesa.net/varim/varim.html, and source can be downloaded directly from that site.

**Comment by n8jja** [comment]
Thank you!

I was able to find it and will take a gander at it this weekend.

I appreciate you all providing the ideas and links!

Jeremy
N8JJA
