### ISSUE TITLE
VARA FM broken on master?

### ISSUE THREAD

**Issue by martinhpedersen** [n8jja/Pat-Vara#23]
See this thread by @km4ack: https://groups.google.com/g/pat-users/c/n_CrqKwhcFE

@xylo04 Maybe we could start by identifying the diff (if any) between the beta version Jason is running and the one released with v0.13.0?

@km4ack Could you please provide the output of pat version from the v0.12.1 that is working with VARA FM?

Thanks!

**Comment by km4ack** [comment]
Pat v0.12.1 (45c5064) linux/arm - go1.18

I also posted some additional details on [the forum](https://groups.google.com/g/pat-users/c/n_CrqKwhcFE/m/BdOh7t_AAAAJ)

**Comment by km4ack** [comment]
It is a config.json issue. I added the following two sections to my config file and everything is working now including rig control. I think I fat fingered something earlier when rig control wasn't working.

  "varafm": {
    "host": "localhost",
    "cmdPort": 8300,
    "dataPort": 8301,
    "rig": "my-rig",
    "ptt_ctrl": true
  },
  "varahf": {
    "host": "localhost",
    "cmdPort": 8300,
    "dataPort": 8301,
    "rig": "my-rig",
    "ptt_ctrl": true
  }, 

During the beta, I had added 
  "vara": {
    "host": "localhost",
    "cmdPort": 8300,
    "dataPort": 8301,
    "rig": "my-rig",
    "ptt_ctrl": true
  }, 

but realized that this needed to be changed in 0.13.

**Comment by martinhpedersen** [comment]
Thanks for the clarification @km4ack 🙂 I guess the config structure was changed some time during the development.

FYI - [This PR](https://github.com/la5nta/pat/pull/370) is kind of related. It loads the default config values if `varahf:` and/or `varafm:` is missing in the config, which it will be for most existing installs.

**Comment by martinhpedersen** [comment]
I guess we could close this issue, but we should probably look into the `got a vara command I wasn't expecting: WRONG` error you also reported in the pat-users thread.

```
pat connect varafm:///WC4EOC-8
2022/08/24 12:17:40 my-rig ready. Dial frequency is 145.050.00 MHz.
2022/08/24 12:17:40 Connecting to WC4EOC-8 (varafm)...
2022/08/24 12:17:40 got a vara command I wasn't expecting: WRONG
2022/08/24 12:17:43 Connected to WC4EOC-8 (vara)
Williamson County TN EMA
[WL2K-5.0-B2FWIHJM$]
```

**Comment by km4ack** [comment]
Agree this thread should be closed. Not sure what is causing the `2022/08/24 12:17:40 got a vara command I wasn't expecting: WRONG` error. I never saw it when using 0.12.1. Only after upgrading to 0.13.0. To my knowledge, everything else is working as expected after adding the additional sections to the config file.

**Comment by xylo04** [comment]
The `got a vara command I wasn't expecting: WRONG` error is coming from VARA FM because VARA FM doesn't support the `CWID ON` command added [here](https://github.com/n8jja/Pat-Vara/pull/17/files#diff-dcfbe62325acb1e5f8315c63cd5137ddbc69488402b303f1c5e0daf984de0411R39), only the HF modem supports that command.
