### ISSUE TITLE
Panic if VARA is unregistered

### ISSUE THREAD

**Issue by xylo04** [n8jja/Pat-Vara#25]
See https://github.com/la5nta/pat/issues/371#issuecomment-1241946454. We thought the `REGISTERED` response would always have a callsign, but it looks like it's still sent even when there's no callsign. This causes a slice bounds out of range:

```
panic: runtime error: slice bounds out of range [11:10]
github.com/n8jja/Pat-Vara/vara.(*Modem).handleCmd(0xc00028c120, {0xc0000a2060, 0xa})
/go/pkg/mod/github.com/n8jja/!pat-!vara/vara@v0.0.0-20220513234311-0b0963c08629/vara.go:232 +0x3b0
```

To work around, @martinhpedersen recommends using `strings.Split`.

**Comment by martinhpedersen** [comment]
Not sure if my suggestion to use strings.Split would make it any better 😅

Maybe something like this? https://go.dev/play/p/qvH0f5ndeUI
