### ISSUE TITLE
Should we merge this into wl2k-go?

### ISSUE THREAD

**Issue by martinhpedersen** [n8jja/Pat-Vara#32]
Hi @n8jja,

First of all, thank you for kickstarting this transport package and helping us add support for Vara in Pat 🎉.

I've submitted a few PRs resolving some issues that I'd really like to include in the next release of Pat. However, I haven't gotten any response to the PRs since I worked on these issues a month ago, and so they remain unmerged and unreleased.

Although you started this repo, I guess we never asked you officially if you wanted to be the maintainer of this code over time. Is this something you want to do, or should we merge this code into github.com/la5nta/wl2k-go?

Thanks again for all your work! 🙂 

73 de LA5NTA / Martin

**Comment by n8jja** [comment]
Hey!

Apologies...for some reason, I was not getting the PR notifications in my email.  I'd be happy to maintain the repo, and even work on some documentation.  At the same time, I wouldn't be upset if you thought it was better to fold it into the main codebase.  I'm no expert at Go, so my few efforts to make actual code changes haven't gone so well... 🙂

Let me know your thoughts and I'll get on those PR's today.  Thanks!

Jeremy
N8JJA

**Comment by martinhpedersen** [comment]
No worries @n8jja 🙂 Thanks for accepting the PRs!

It'd be great if you can continue maintaining this code. Less code to maintain in the project is a good thing I think 👍 Thanks!

**Comment by n8jja** [comment]
Happy to help!  Thanks for your patience and let me know if I'm missing
anything else.  I've not maintained a repo like this before, so I'm still
learning.

Jeremy
N8JJA
