### ISSUE TITLE
Delete tag `V1.1.1`

### ISSUE THREAD

**Issue by martinhpedersen** [n8jja/Pat-Vara#40]
It seems having two different tags that only differs on casing `v1.1.1, V1.1.1` is not a good idea. Probably because tags are represented as files in the `.git` directory, and some file systems are case insensitive. The fact that they point to different commits does not help either 😅 

Every time I pull now, I get these messages:

```
git pull
From github.com:n8jja/Pat-Vara
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.1     -> v1.1.1
```

Maybe it's worth trying to delete the misspelled `V1.1.1` tag (`git push --delete origin V1.1.1`) 🙂

**Comment by n8jja** [comment]
Tag has been deleted and proper one applied!
