### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by martinhpedersen** [n8jja/Pat-Vara#8]
Hi!

First of all: Thank you!!

I noticed that there is no license declaration included in this repo. Please consider adding one. This will be required in order for us to distribute this as part of Pat.

My best suggestion would be The MIT License or something similar. GPL will not suffice since Go applications are linked statically and Pat is not GPL licensed.

https://medium.com/@henvic/opensource-and-go-what-license-f6b36c201854

**Comment by n8jja** [comment]
Hi Martin!

Glad to help!  I have added the license.  Thanks for pointing this out.

- Jeremy
  N8JJA
